import { Article } from './types';

// Helper para criar datas recentes dinamicamente
const generateRecentDate = (daysAgo: number, hour: number, minute: number): string => {
  const date = new Date();
  date.setDate(date.getDate() - daysAgo);
  date.setHours(hour, minute, Math.floor(Math.random() * 60));
  return date.toISOString();
};

export const MOCK_ARTICLES: Article[] = [
    // --- ARTIGOS DE ESPORTE ---
    {
        category: 'PÓDIO 520',
        topic: 'sport',
        title: 'Lucas Pinheiro faz história e se torna o primeiro brasileiro campeão em etapa da Copa do Mundo de Esqui Alpino',
        slug: 'lucas-pinheiro-historia-esqui-alpino',
        summary: 'O esquiador Lucas Pinheiro fez história ao se tornar o primeiro brasileiro a vencer uma etapa da Copa do Mundo de Esqui Alpino, com uma performance dominante na Finlândia.',
        content: `<p>O esporte brasileiro amanheceu com um feito simplesmente gigante neste domingo. O esquiador Lucas Pinheiro escreveu seu nome na história ao conquistar uma vitória inédita para o país: ele se tornou o primeiro brasileiro campeão de uma etapa da Copa do Mundo de Esqui Alpino.</p><p>Com uma performance impecável, Pinheiro dominou a prova de slalom em Levi, na Finlândia, superando os favoritos e mostrando que o Brasil pode, sim, ser uma potência nos esportes de inverno. A vitória não só garantiu o ouro, mas também colocou o Brasil no mapa de uma das modalidades mais competitivas do mundo.</p><p>A Rádio 520 acompanhou com exclusividade a preparação do atleta e traz os bastidores dessa conquista histórica. Fique ligado para entrevistas e análises completas.</p>`,
        imageUrl: 'https://lncimg.lance.com.br/cdn-cgi/image/width=950,quality=75,fit=pad,format=webp/uploads/2025/11/AFP__20251116__847D6AF__v1__HighRes__SkiAlpineWorldFinMenSlalom-scaled.jpg',
        author: 'Equipe RADIO520',
        publishedAt: generateRecentDate(0, 8, 30),
        likes: 1650,
        hashtags: ['#EsquiAlpino', '#LucasPinheiro', '#TimeBrasil'],
    },
    {
        category: 'FUTEBOL SHOW 520',
        topic: 'sport',
        title: 'Brasil vence Senegal em Londres com boa atuação coletiva e brilho da nova geração',
        slug: 'brasil-vence-senegal-em-londres-com-boa-atuacao-coletiva',
        summary: 'A Seleção Brasileira venceu Senegal por 2 a 0 em amistoso em Londres, com gols de Estêvão e Casemiro, consolidando a preparação para os próximos compromissos.',
        content: `<p>A Seleção Brasileira fez bem o dever de casa no amistoso desta tarde em Londres e levou a melhor sobre Senegal por 2 a 0, num jogo em que a molecada mostrou personalidade e os veteranos deram a firmeza necessária pra controlar o ritmo.</p><p>Com gols de Estêvão, em uma bela jogada individual, e Casemiro, de cabeça, o Brasil construiu a vitória e testou novas formações táticas. O técnico Carlo Ancelotti aproveitou a partida para dar minutos a jovens talentos, que corresponderam com boas atuações.</p><p>O jogo serviu como uma importante etapa na preparação para as eliminatórias da Copa do Mundo, e a atuação coletiva deixou uma impressão positiva na comissão técnica e na torcida.</p>`,
        imageUrl: 'https://p2.trrsf.com/image/fget/cf/500/0/images.terra.com/2025/11/13/brasil-(8)-1hvb39hddlmih.jpg',
        videoUrl: 'https://storage.googleapis.com/web-dev-assets/video-and-source-tags/chrome.mp4',
        author: 'Equipe RADIO520',
        publishedAt: generateRecentDate(2, 15, 0),
        likes: 1100,
        hashtags: ['#SeleçãoBrasileira', '#Futebol', '#Amistoso'],
    },
    {
        category: 'REPÓRTER 520',
        topic: 'sport',
        title: 'Gabriel Magalhães é cortado do amistoso da Seleção Brasileira',
        slug: 'gabriel-magalhaes-cortado-amistoso-selecao',
        summary: 'O zagueiro Gabriel Magalhães, do Arsenal, foi cortado do amistoso da Seleção Brasileira contra a Tunísia em Londres após sentir uma lesão na coxa. Carlo Ancelotti optou por não convocar um substituto.',
        content: `<p>O clima em Londres deu aquela azedada pra Seleção Brasileira. O zagueiro Gabriel Magalhães, do Arsenal, sentiu a coxa direita e tá oficialmente fora do amistoso contra a Tunísia. O defensor deixou a preparação e já retorna ao clube inglês pra continuar o tratamento.</p><p>A lesão tirou Gabriel da lista às vésperas do jogo, e Carlo Ancelotti decidiu não chamar ninguém pro lugar dele — vai com o que tem mesmo. A comissão técnica entende que o grupo atual segura bem a bronca pro compromisso da Data Fifa.</p><p>O corte do defensor é um baque, já que Gabriel vinha de boa fase no Arsenal e tinha moral na Seleção. Agora, o foco do jogador é se recuperar o quanto antes pra voltar ao ritmo na Premier League.</p><p>A cobertura completa da Seleção em Londres você acompanha aqui, no Repórter 520, na Rádio 520.</p>`,
        imageUrl: 'https://admin.cnnbrasil.com.br/wp-content/uploads/sites/12/2025/11/gabriel-magalhaes-lesionado-brasil-senegal-e1763312078525.jpg?w=1200&h=630&crop=1',
        author: 'Repórter 520',
        publishedAt: generateRecentDate(1, 10, 15),
        likes: 980,
        hashtags: ['#SeleçãoBrasileira', '#GabrielMagalhães', '#Lesão'],
        isFeatured: true, // Artigo em destaque na seção de esportes
    },
     {
        category: 'REPÓRTER 520',
        topic: 'sport',
        title: 'Esquema clandestino de venda de materiais do Corinthians é confirmado após denúncia anônima',
        slug: 'esquema-venda-materiais-corinthians-confirmado',
        summary: 'Uma investigação interna do Corinthians confirmou a existência de um esquema clandestino de comércio de materiais oficiais do clube, tocado por funcionários do próprio clube.',
        content: `<p>Uma investigação interna do Corinthians confirmou a existência de um esquema clandestino de comércio de materiais oficiais do clube — incluindo peças fornecidas pela Nike — rolando tanto dentro quanto fora das dependências alvinegras. A apuração começou após uma denúncia anônima e, segundo o relatório final, não só era real como estava sendo tocada por funcionários do próprio clube. Bem bizarro.</p><p>A auditoria teria encontrado provas concretas de que produtos estavam sendo desviados do estoque oficial e revendidos de forma ilegal. Um dos funcionários envolvidos, cujo nome não foi revelado no documento, chegou a ser flagrado vendendo camisas e outros itens do Timão por valores entre R$ 150 e R$ 180. Confrontado, ele acabou admitindo participação no esquema de desvio e revenda.</p><p>O caso acende de novo o alerta sobre gestão interna, controle de patrimônio e possíveis novos desdobramentos disciplinares. O Corinthians ainda não se pronunciou oficialmente sobre punições, mas a expectativa é que o clube adote medidas internas nos próximos dias.</p><p>A apuração foi divulgada inicialmente pelo ge, e fotos do material supostamente envolvido no esquema circularam nas redes sociais, aumentando ainda mais a pressão sobre a diretoria.</p>`,
        imageUrl: 'https://admin.cnnbrasil.com.br/wp-content/uploads/sites/12/2024/08/camisa_corinthians_1-e1724771296103.png?w=1200&h=1200&crop=1',
        author: 'Repórter 520',
        publishedAt: generateRecentDate(0, 9, 15),
        likes: 850,
        hashtags: ['#Corinthians', '#Futebol', '#Esquema'],
    },
     {
        category: 'VOLTA RÁPIDA',
        topic: 'sport',
        title: 'Brasil no topo: Diogo Moreira comemora título mundial ao som de “Charlie Brown”, clássico de Benito de Paula',
        slug: 'diogo-moreira-comemora-titulo-mundial-charlie-brown',
        summary: 'O motociclismo brasileiro vive um momento histórico com a conquista do primeiro título mundial de Diogo Moreira na Moto2.',
        content: `<p>O motociclismo brasileiro vive um momento que muda a história do esporte no país. <strong>Diogo Moreira</strong> conquistou o primeiro título mundial do Brasil, encerrando sua temporada da Moto2 com uma performance sólida em Valência — e uma comemoração absolutamente brasileira dentro do paddock.</p><p>Ao som de "Charlie Brown", clássico de Benito de Paula, a equipe celebrou o feito histórico, que coloca o Brasil em um novo patamar na motovelocidade mundial. A conquista coroa uma temporada de consistência e talento do jovem piloto.</p>`,
        imageUrl: 'https://pbs.twimg.com/media/G539Wp0WUAASsDL?format=jpg&name=large',
        author: 'Equipe RADIO520',
        publishedAt: generateRecentDate(1, 14, 0),
        likes: 1250,
        hashtags: ['#DiogoMoreira', '#Moto2', '#CampeãoMundial'],
    },
    {
        category: 'ACE 520',
        topic: 'sport',
        title: 'Sinner conquista segundo ATP Finals seguido e consolida domínio na nova geração',
        slug: 'sinner-conquista-segundo-atp-finals-seguido-e-consolida-dominio-na-nova-geracao',
        summary: 'Jannik Sinner vence Carlos Alcaraz, conquista o bicampeonato do ATP Finals em Turim e consolida seu domínio na nova geração do tênis masculino.',
        content: `<p>Jannik Sinner confirmou, neste domingo, a fase dominante que vive no circuito ao conquistar seu segundo título consecutivo do Nitto ATP Finals, derrotando Carlos Alcaraz por 7-6 e 7-5, em Turim.</p><p>O italiano mostrou um tênis de altíssimo nível, com saques potentes e uma consistência impressionante do fundo da quadra. A vitória sobre Alcaraz, em uma final muito aguardada, solidifica Sinner como a principal força da nova geração do tênis masculino e o coloca como um dos favoritos para os Grand Slams da próxima temporada.</p>`,
        imageUrl: 'https://www.atptour.com/-/media/images/news/2025/11/16/21/34/sinner-nitto-atp-finals-2025-title-reaction-image.jpg',
        author: 'Análise 520',
        publishedAt: generateRecentDate(0, 7, 0),
        likes: 1400,
        hashtags: ['#ATPFinals', '#Tênis', '#Sinner', '#Alcaraz'],
    },

    // --- ARTIGOS ESPECIAIS ---
    {
        category: 'CINECAST 520',
        topic: 'special',
        title: 'MLS VAI MIGRAR TODOS OS JOGOS PARA O PACOTE PRINCIPAL DO APPLE TV A PARTIR DE 2026',
        slug: 'mls-migra-jogos-apple-tv-2026',
        summary: 'A partir de 2026, a MLS vai incluir todos os jogos no pacote padrão do Apple TV, eliminando o MLS Season Pass e ampliando o acesso para todos os assinantes da plataforma.',
        content: `<p>A Major League Soccer (MLS) anunciou uma mudança significativa na sua estratégia de distribuição de conteúdo. A partir de 2026, todos os jogos da liga — incluindo temporada regular, Leagues Cup, MLS All-Star Game, Campeones Cup e os playoffs da MLS Cup — passarão a fazer parte do pacote padrão do Apple TV, sem custo adicional além da assinatura mensal da plataforma.</p><p>Com isso, a liga norte-americana encerra o atual modelo do MLS Season Pass, serviço exclusivo lançado em parceria com a Apple em 2023 e que exigia uma assinatura separada. Agora, o acesso ao conteúdo será ampliado para todo assinante da Apple TV, hoje no valor de US$ 12,99 por mês.</p><p>A decisão busca aumentar o alcance da MLS dentro do ecossistema Apple, depois de repetidas avaliações internas sobre engajamento, retenção e conversão do público — especialmente após a chegada de Lionel Messi, que elevou consideravelmente o interesse global na liga.</p><p>Outra mudança relevante envolve os torcedores que compram carnês de ingressos anuais. A partir de 2026, os season-ticket holders vão ganhar uma assinatura anual do Apple TV, substituindo o benefício anterior, que era o acesso gratuito ao MLS Season Pass.</p><p>O movimento reforça a estratégia da Apple de consolidar um portfólio esportivo robusto dentro do Apple TV+, além de facilitar a experiência do usuário ao reduzir fragmentação de assinaturas. No entanto, parte da base de fãs já demonstra preocupação com o custo anual, já que o modelo antigo permitia comprar o pacote da MLS de forma isolada.</p><p>A MLS e a Apple ainda não comentaram sobre possíveis impactos dessa alteração em acordos com emissoras tradicionais, como Fox Sports, que também detém direitos de transmissão no mercado norte-americano.</p><p>A Rádio 520 segue acompanhando os bastidores dessa transição e os próximos passos do acordo bilionário entre MLS e Apple.</p>`,
        imageUrl: 'https://images.mlssoccer.com/image/private/t_editorial_landscape_8_desktop_mobile/mls-atl/r8z7x8uhlc5v9mstz2oq.webp',
        author: 'Redação 520',
        publishedAt: generateRecentDate(0, 15, 30),
        likes: 1500,
        hashtags: ['#MLS', '#AppleTV', '#Futebol', '#Streaming'],
    },
    {
        category: 'SPORTS BUSINESS 520',
        topic: 'special',
        title: 'Pai de Neymar compra marca de Pelé por US$ 18 milhões',
        slug: 'pai-de-neymar-compra-marca-pele',
        summary: 'Neymar da Silva Santos, pai de Neymar Jr., adquiriu os direitos da marca Pelé por US$ 18 milhões através da NR Sports. O acordo marca um movimento significativo no marketing esportivo global.',
        content: `<p>O universo do marketing esportivo ganhou um movimento pesado nesta semana. Neymar da Silva Santos, pai do atacante Neymar Jr., desembolsou US$ 18 milhões — algo em torno de R$ 95 milhões na cotação atual — para adquirir os direitos da marca Pelé, pertencente ao Rei do Futebol, falecido em 2022.</p><p>A negociação foi feita por meio da NR Sports, empresa da família Neymar, após tratativas com a norte-americana Sport 10, antiga detentora da marca. Segundo informações reveladas pelo UOL, o acordo foi fechado ainda em novembro.</p><p>O anúncio oficial está marcado para esta quarta-feira (19 de novembro), justamente no aniversário do milésimo gol de Pelé — uma data carregada de simbolismo para o futebol mundial.</p><p>A reportagem também aponta que a transação foi “facilitada” porque a marca Pelé vinha sendo pouco explorada comercialmente nos últimos anos. A NR Sports, que já administra a imagem de Neymar Jr., agora passa a controlar também um dos nomes mais valiosos e icônicos da história do esporte.</p><p>A aquisição levanta questionamentos no mercado: qual será o plano da família Neymar para reposicionar a marca Pelé? Vem rebranding? Licenciamentos globais? Projetos digitais? O potencial é gigante — e o impacto, inevitável.</p>`,
        imageUrl: 'https://lncimg.lance.com.br/cdn-cgi/image/width=1280,height=720,quality=75,fit=cover,format=webp/uploads/2025/11/neymar-pai-aspect-ratio-512-320.jpg',
        author: 'Análise 520',
        publishedAt: generateRecentDate(0, 11, 0),
        likes: 1800,
        hashtags: ['#SportBusiness', '#Neymar', '#Pelé', '#MarketingEsportivo'],
        isFeatured: true,
    },
    {
        category: 'RADIO520 FASHION LEAGUE',
        topic: 'special',
        title: 'ADIDAS APRESENTA PRIMEIRA COLEÇÃO DO TIME BRASIL PARA OS JOGOS DE INVERNO DE 2026',
        slug: 'adidas-apresenta-colecao-time-brasil-jogos-inverno-2026',
        summary: 'A Adidas revelou a primeira coleção para o Time Brasil nos Jogos Olímpicos de Inverno de 2026, marcando sua estreia como fornecedora oficial. Os uniformes destacam as cores nacionais e reforçam a busca do Brasil por seu primeiro pódio no evento.',
        content: `<p>A Adidas revelou oficialmente sua primeira coleção desenvolvida para o Comitê Olímpico do Brasil (COB) e para o Time Brasil nos Jogos Olímpicos de Inverno de Milano-Cortina 2026. A competição acontece em fevereiro do próximo ano e marcará a estreia da marca alemã como fornecedora de material esportivo dos atletas brasileiros em eventos olímpicos de inverno.</p><p>A coleção faz parte do acordo firmado em maio de 2025, quando a Adidas assumiu o fornecimento oficial dos uniformes de nove comitês olímpicos ao redor do mundo — incluindo o brasileiro. Para o Time Brasil, será a primeira chance de vestir as três listras em momentos de destaque, como cerimônias, pódios, treinos, viagens e apresentações oficiais.</p><p>O visual dos uniformes mantém a identidade nacional como ponto central. O tom predominante é o verde petróleo, acompanhado de detalhes em branco e com a palavra “Brasil” aplicada na vertical. Algumas peças de passeio trazem também acabamentos em amarelo, compondo uma paleta que remete diretamente às cores da bandeira.</p><p>O lançamento reforça a expectativa do COB para Milano-Cortina. O Brasil busca seu primeiro pódio na história dos Jogos de Inverno, algo que seria ainda mais simbólico estreando o novo uniforme.</p><p>A Rádio 520 segue acompanhando todas as novidades do Time Brasil rumo a 2026.</p>`,
        imageUrl: 'https://conteudo.imguol.com.br/c/esporte/d1/2025/05/12/ginga-durante-o-anuncio-da-parceria-entre-cob-e-adidas-1747085316478_v2_1x1.jpg',
        author: 'Redação 520',
        publishedAt: generateRecentDate(0, 16, 0),
        likes: 1600,
        hashtags: ['#TimeBrasil', '#Adidas', '#OlimpíadasDeInverno', '#ModaEsportiva'],
    },
    {
        category: 'RESENHA 520',
        topic: 'special',
        title: 'GABIGOL MANDOU “SINAL”? AH, ME AJUDA A TE AJUDAR, PEIXE…',
        slug: 'gabigol-sinal-santos-resenha',
        summary: 'Rudy da Galera analisa os supostos "sinais" de Gabigol para o Santos e a realidade do mercado da bola. Uma opinião sem papas na língua sobre a novela que agita a torcida santista.',
        content: `<p><strong>por RUDY DA GALERA, OPINIÃO SEM PAPAS NA LINGUA</strong></p><p>Rapaziada, olha o nível da novela: o Santos tá dizendo que vê “sinais” de Gabigol. Sim, isso aí mesmo. “Sinais”. Tipo previsão do tempo, signo, mapa astral? Porque se depender de futebol, contrato e realidade, o único sinal mesmo é o de “não ultrapasse”.</p><p>O cara tá no Cruzeiro, tem contrato até 2028, ganha uma bala, e os caras ainda tão nessa de interpretar gesto de Kings League como se fosse declaração de amor? Por favor, né.</p><p>A real é simples:<br>➡️ Se o Santos não cair, dá pra sonhar.<br>➡️ Se vender Tiquinho, dá pra pensar.<br>➡️ Se tiver dinheiro, dá pra conversar.<br>➡️ Mas pra tirar ele do Cruzeiro? Aí, meu amigo… precisa de muita fé, pix gordo e uma diretoria com coragem — coisas que o Santos não anda mostrando ultimamente.</p><p>E não vamos fingir que não lembramos do começo do ano: o Peixe tentou contratar o homem, e ele escolheu ir pro Cruzeiro. Isso aí dói mais que perder clássico no último minuto, mas é fato. Marcelo Teixeira ficou chateado? Ficou. Quem não ficaria? Só que futebol não é terapia, é mercado. E no mercado quem tem a grana e o contrato forte manda no jogo.</p><p>Agora, a parte mais hilária:<br>Gabigol, na Kings League, soltou que “o Santos não cai”, que “ganha do Palmeiras”, que “vai ajudar o Cruzeiro”… Mano, isso aí não é sinal pra voltar, isso é só o Gabi sendo o Gabi — causando, fazendo graça e jogando pro entretenimento.</p><p>O Santos tá certo em esperar o calendário de 2026 pra falar de reforço. Também tá certo em sonhar — torcedor vive de esperança. Mas interpretar brincadeira como possibilidade real de retorno? Aí já é o famoso se iludir com o crush que curtiu seu story.</p><p>Pra trazer o Gabigol de volta, o Peixe não precisa só de “sinal”.<br>Precisa de planejamento, ousadia e caixa — e hoje o Santos tem só a primeira palavra, e bem mal escrita.</p><p>O Rudy Galera volta a qualquer momento, porque o futebol brasileiro NUNCA deixa a gente descansar.</p>`,
        imageUrl: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTk6TiM9afvdz-z6m98yabY2-ph7JEDxHZNRg&s',
        author: 'Rudy da Galera',
        publishedAt: generateRecentDate(0, 10, 30),
        likes: 1750,
        hashtags: ['#Gabigol', '#SantosFC', '#Cruzeiro', '#FutebolBrasileiro', '#Resenha520'],
    },
     {
        category: 'RÁDIO520 E-NEWS',
        topic: 'special',
        title: 'INSTAGRAM TESTA OCULTAR A LISTA DE “SEGUINDO” EM BUSCA DE MAIS PRIVACIDADE',
        slug: 'instagram-testa-ocultar-lista-seguindo-privacidade',
        summary: 'O Instagram começou a testar a ocultação da lista de "seguindo" para alguns usuários, visando maior privacidade. A medida divide opiniões e ainda não tem data para ser implementada globalmente.',
        content: `<p>O Instagram começou a liberar, para alguns usuários, um novo teste que promete mexer no uso diário da plataforma: a ocultação da lista de “seguindo”. Na prática, isso significa que não será mais possível ver quem determinadas contas seguem — algo que sempre foi público desde o início da rede social.</p><p>A mudança, relatada por usuários em vários países, faz parte de um movimento do Instagram em direção a maior proteção de dados e privacidade. A empresa ainda não confirmou quando (ou se) a novidade será aplicada globalmente.</p><p>A atualização já está gerando repercussão: enquanto alguns usuários comemoram o reforço de privacidade, outros criticam dizendo que a plataforma “perde graça” sem esse nível de transparência. Nos comentários da publicação original, não faltaram reações bem-humoradas, críticas à plataforma e até comparações com concorrentes, como o TikTok.</p><p>O Instagram segue testando novas funções de forma gradual, como tem feito nos últimos anos para ajustar o comportamento da rede e responder às pressões por segurança digital.</p>`,
        imageUrl: 'https://images.unsplash.com/photo-1595039838779-f3780873afdd?fm=jpg&q=60&w=3000&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Mnx8aW5zdGFncmFtfGVufDB8fDB8fHww',
        author: 'Redação 520',
        publishedAt: generateRecentDate(0, 14, 0),
        likes: 1300,
        hashtags: ['#Instagram', '#Privacidade', '#RedesSociais', '#Tecnologia'],
    },
    {
        category: 'ESPECIAIS',
        topic: 'special',
        title: 'Podcast 520: Analisando as batidas que vão dominar o verão',
        slug: 'podcast-520-batidas-verao',
        summary: 'No novo episódio do Podcast 520, nossos especialistas dissecam as tendências sonoras para o verão, do funk ao afrobeat. Dê o play e prepare sua playlist.',
        content: `<p>O verão está chegando e com ele uma nova trilha sonora. No episódio desta semana do Podcast 520, reunimos nossos especialistas para uma análise profunda do que vai bombar nas pistas e nos fones de ouvido.</p><p>Discutimos a ascensão do afrobeat no Brasil, a evolução do funk e as colaborações internacionais que prometem agitar a estação. Também montamos uma playlist exclusiva com nossas apostas. Este é o guia definitivo para você não ficar de fora das batidas que vão definir a temporada.</p>`,
        imageUrl: 'https://images.unsplash.com/photo-1511671782779-c97d3d27a1d4?q=80&w=2070&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D',
        audioUrl: 'https://open.spotify.com/episode/3q8B9gA4sX5bY5Z0w8jX9a',
        author: 'Equipe RADIO520',
        publishedAt: generateRecentDate(1, 18, 0),
        likes: 850,
        hashtags: ['#Podcast', '#Música', '#Verão2025', '#Playlist'],
    },
];